name: Automated_CMS
on:
  schedule:
    - cron: '0 * * * *' # يعمل كل ساعة
  workflow_dispatch: # للتشغيل اليدوي
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # للسماح للبوت بالكتابة في المستودع
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install axios cheerio @google/generative-ai
      - name: Run Bot
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        run: node bot.js
      - name: Commit & Push Changes
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "bot@github.com"
          git add data.json
          git commit -m "Auto-update: New App Detected" || exit 0
          git push
          
